#:schema node_modules/wrangler/config-schema.json
name = "comments-r2"
compatibility_date = "2024-12-30"
pages_build_output_dir = "./build/client"

######## PRODUCTION environment config ########

# [env.production.vars]
# AUTH_KEY_SECRET = "ENTER_AUTH_KEY_HERE"